### ISSUE TITLE
FIX template to have the nice documentation icons back

### ISSUE THREAD

**Issue by yada** [microcks/microcks.io#192]
### Reason/Context

Look like we lost the doc menu icons during the migration process, template sync or issue to fix.

### Description

Missing doc menu icons:
<img width="743" alt="Capture d’écran 2024-06-28 à 13 53 28" src="https://github.com/microcks/microcks.io/assets/552526/27219270-73eb-43b2-8a04-a53f3cbe2f3d">

### Implementation ideas

It should be like this on the preview site:
ref: https://microcks-io.vercel.app/documentation/
<img width="637" alt="Capture d’écran 2024-06-28 à 13 54 46" src="https://github.com/microcks/microcks.io/assets/552526/832dfddd-1cec-4769-861b-d743fabd169f">

**Comment by lbroudoux** [comment]
This is a side effect of migrating to Hugo 0.127.0. The fix is the same than in #170.
