### ISSUE TITLE
WARN  deprecated: .Site.DisqusShortname was deprecated in Hugo v0.120.0

### ISSUE THREAD

**Issue by yada** [microcks/microcks.io#199]
### Reason/Context

The latest Hugo version (well, since 1.120.0, which was released on [Oct 30, 2023](https://github.com/gohugoio/hugo/releases/tag/v0.120.0)) reports this deprecated issue:

> WARN  deprecated: .Site.DisqusShortname was deprecated in Hugo v0.120.0 and will be removed in a future release. Use .Site.Config.Services.Disqus.Shortname instead.

### Description

This is not a critical update, but it is good to manage it up front and not wait for it to be decommissioned, as we rely on Disqus for the website blog post comments.

### Implementation ideas

Based on Hugo's documentation:
https://gohugo.io/methods/site/disqusshortname/
https://gohugo.io/methods/site/config/

I have tested this simple update locally:
```
% diff themes/microcks/layouts/_default/single.html themes/microcks/layouts/_default/single.html.PATCHED
34c34
<         {{ if site.DisqusShortname }}
---
>         {{ if .Site.Config.Services.Disqus.Shortname }}
```

And it should work. No more WARN was reported when using Hugo. But need to be **tested on the deployed** site as:
<img width="874" alt="Capture d’écran 2024-06-28 à 17 35 07" src="https://github.com/microcks/microcks.io/assets/552526/3042f522-c75e-4a94-951d-89a02f75fda1">

**Comment by yada** [comment]
@lbroudoux for input before committing this update.

**Comment by lbroudoux** [comment]
LGTM. You can commit this and I'll deploy a new version of the website.
