### ISSUE TITLE
Replace twitter by X in web page footer (icons)

### ISSUE THREAD

**Issue by yada** [microcks/microcks.io#233]
### Reason/Context

Replace "Twitter" with "X" to reflect the platform's rebranding. This change ensures consistency and accuracy in how we refer to social media channels, keeping our content up to date with the latest industry changes.

### Description

Just change and replace the footer icon.

### Implementation ideas

See if an X icon exists for the footer:
<img width="1344" alt="X" src="https://github.com/user-attachments/assets/5719dd95-0712-4413-a812-bbbabef82d25">

**Comment by ericklasluisa** [comment]
Hi, I would like to take on this issue and help update the footer to reflect the rebranding from "Twitter" to "X." I'll look into replacing the footer icon and ensuring consistency with the current branding.

**Comment by yada** [comment]
Welcome @ericklasluisa I happy to review your PR and merge it, looking forward to it.
