### ISSUE TITLE
Replace Twitter by X on the community about page

### ISSUE THREAD

**Issue by yada** [microcks/microcks.io#234]
### Reason/Context

Replace "Twitter" with "X" to reflect the platform's rebranding. This change ensures consistency and accuracy in how we refer to social media channels, keeping our content up to date with the latest industry changes.

### Description

Replace "Twitter" with "X" 

### Implementation ideas

Change URL and Text here:
https://microcks.io/community/
Section: "Follow us on social"
<img width="1255" alt="Xbis" src="https://github.com/user-attachments/assets/ebebd44b-63d5-49ac-a155-67dec67c932d">

**Comment by mchen610** [comment]
I will do this!

**Comment by yada** [comment]
Welcome @mchen610 I look forward to review and merge 🙌

**Comment by mchen610** [comment]
> Welcome @mchen610 I look forward to review and merge 🙌

Thank you! Do you think you could create a more complex issue for me to solve too?

**Comment by yada** [comment]
> > Welcome @mchen610 I look forward to review and merge 🙌
> 
> Thank you! Do you think you could create a more complex issue for me to solve too?

Let's start with this simple issue ;-) and then, please check all the issues in our repos, we have many ways to contribute ;)

**Comment by yada** [comment]
Thank you @mchen610
