### ISSUE TITLE
Hugo and site config key paginate deprecated: update todo

### ISSUE THREAD

**Issue by yada** [microcks/microcks.io#246]
### Reason/Context

WARN  deprecated: site config key paginate was deprecated in Hugo v0.128.0 and will be removed in a future release. Use pagination.pagerSize instead.

This is coming from ".Site.DisqusShortname" usage.

### Description

We need to address this warning because the paginate configuration key in Hugo was deprecated in version 0.128.0. Continuing to use it could result in broken functionality in future releases when it's removed. To ensure our site remains compatible and functions smoothly with future Hugo updates, we should update the key to pagination.pagerSize. 

### Implementation ideas

Info here:
https://discourse.gohugo.io/t/pagination-deprecated-error/51571/2

**Comment by ahmedkhalid7** [comment]
Hi @yada, I wanted to start contributing to open source projects, and I came across your issue to start with. I think I understand what the issue is, but I can't completely grasp what the solution would be. Is it simply to replace any occurrence of .Site.DisqusShortname with pagination.pagerSize throughout the entire Microcks repository?

**Comment by yada** [comment]
Thanks for reaching out and welcome. Yes it looks like a query replace on website should work. Please fork and test using the Hugo server command to see if it solve the issue and all pages are still working as expected.

**Comment by yada** [comment]
This is more related to https://gohugo.io/extras/pagination/ and the global Hugo configuration.
See configuration file config/_default/hugo.toml
```
# post pagination
paginate = 6 # see https://gohugo.io/extras/pagination/
```

I have tested using:
`pagination.pagerSize = 6`

And it seems to sort out the deprecated error message.

@ahmedkhalid7 can you investigate and check this? It could be an easy contribution, but it is an excellent way to practice and sign the PR (see DCO check, which is mandatory). I'll be happy to merge.
