### ISSUE TITLE
Add APIQuality logo to adopters carousel at the main page

### ISSUE THREAD

**Issue by APIQuality-io** [microcks/microcks.io#260]
### Reason/Context

As we talked, we would like to appear in the carousel of logos at the main page with our logo APIQuality, as we are adopters of Microcks. 

### Description

Add APIQuality's logo to the carousel at the main page: 
<img width="140" alt="logo-apiquality-cuadrado" src="https://github.com/user-attachments/assets/3f0dcd1f-4731-4991-903e-51a5b3eb5b94" />

**Comment by yada** [comment]
Thanks, @APIQuality-io,
The website content has been updated and should be online soon (we need to deploy the site).
