### ISSUE TITLE
Improve the jenkins plugin documentation

### ISSUE THREAD

**Issue by nmasse-itix** [microcks/microcks.io#4]
The documentation about the jenkins plugin (https://microcks.io/documentation/automating/jenkins/) gives the command to create the build config but does not explain how to use the resulting image in jenkins.

The following two commands update an jenkins deploymentconfig to use the custom image:

```sh
oc set triggers dc/jenkins --remove --from-image=openshift/jenkins:2
oc set triggers dc/jenkins --from-image=microcks-jenkins-master:latest -c jenkins
```

**Comment by lbroudoux** [comment]
Done. Thanks @nmasse-itix for the suggestion!
