### ISSUE TITLE
New versions of minikube install ingress into a different namespace

### ISSUE THREAD

**Issue by khuong507** [microcks/microcks.io#49]
New versions of kind installs the deployment in the ingress-nginx namespace when running minikube addons enable ingress as per https://kubernetes.io/docs/tasks/access-application-cluster/ingress-minikube/

**Comment by khuong507** [comment]
Here is the updated doc https://github.com/microcks/microcks.io/pull/48

**Comment by lbroudoux** [comment]
Sorry for sooo long delay... Thank you!
