### ISSUE TITLE
https://microcks.io/discord-invite (social footer icon) is not working

### ISSUE THREAD

**Issue by yada** [microcks/microcks.io#65]
### Describe the bug

In params.toml
```
[[social]]
title = "Discord"
icon = "fab fa-discord" # themify icon : https://themify.me/themify-icons
link = "https://microcks.io/discord-invite"
```

But this redirect (in discord-invite/_index.md) is not working:
```
---
title: "Microcks Discord Invite"
layout: "redirect"
target: "https://discord.gg/JA4rbcGzk7"
---
```

### Expected behavior

Should redirect to https://discord.gg/JA4rbcGzk7

### Actual behavior

No redirection and blank page:
<img width="1346" alt="Capture d’écran 2024-02-03 à 18 26 06" src="https://github.com/microcks/microcks.io/assets/552526/f2a5fe62-658f-4927-a329-96fcca12598a">

### How to Reproduce?

Just click here: https://microcks.io/discord-invite/

### Additional information

I can easily do a PR on this and:

1. delete "discord-invite/_index.md"
2. replace "https://microcks.io/discord-invite" with "https://discord.gg/JA4rbcGzk7" in params.toml

**Comment by lbroudoux** [comment]
Think we lost the `redirect` layout somewhere during the migration. We must restore it because it also breaks the redirection to the Golang packages.

**Comment by yada** [comment]
Yep I Forget the golang package was also using this layout, good point 🙌
