### ISSUE TITLE
Links to "organizing the Microcks repository" leads to old ui view

### ISSUE THREAD

**Issue by soGit** [microcks/microcks.io#73]
### Describe the bug

"organizing repository" leads to https://microcks.io/documentation/using/advanced/organizing/

**Comment by yada** [comment]
I appreciate you bringing this up, @soGit 
@lbroudoux, it seems we have some tidying up to do. What do you think about removing https://microcks.io/documentation/using/advanced/organizing/?

**Comment by soGit** [comment]
@yada 

I've created a script to verify relative links. Broken 31 of 162 links:

https://microcks.io/documentation/getting-started-tests/./using/advanced/#content-negocation-in-rest-mocks
https://microcks.io/documentation/automating/github-actions/../using/importers/#multi-artifacts-support
https://microcks.io/documentation/automating/service-account/./cli.md
https://microcks.io/documentation/administrating/secrets/./users
https://microcks.io/documentation/administrating/snapshots/./users
https://microcks.io/documentation/using/dynamic/./advanced/templates
https://microcks.io/documentation/using/tests/./importers/#supported-formats
https://microcks.io/documentation/using/tests/../administrating/secrets
https://microcks.io/documentation/using/metadata/../../openapi/#using-openapi-extensions
https://microcks.io/documentation/using/metadata/../../asyncapi/#using-asyncapi-extensions
https://microcks.io/documentation/using/metadata/../../grpc
https://microcks.io/documentation/using/metadata/../../postman
https://microcks.io/documentation/using/metadata/../../importers/#multi-artifacts-support
https://microcks.io/documentation/using/metadata/../../grpc/#defining-dispatch-rules
https://microcks.io/documentation/using/metadata/../../openapi/#using-openapi-extensions
https://microcks.io/documentation/using/metadata/../../asyncapi/#using-asyncapi-extensions
https://microcks.io/documentation/using/advanced/../automating/api/
https://microcks.io/documentation/using/swagger/../openapi.md
https://microcks.io/documentation/using/monitoring/../../../automating/api
https://microcks.io/documentation/using/monitoring/../../tests#conformance-metrics
https://microcks.io/documentation/using/monitoring/../../../automating/api
https://microcks.io/documentation/using/dispatching/../../mocks
https://microcks.io/documentation/using/dispatching/../administrating/users/
https://microcks.io/documentation/using/organizing/../../../administrating/users/#authorization
https://microcks.io/documentation/using/organizing/../../../administrating/users/#users-management
https://microcks.io/documentation/guides/rabbitmq-support/../../administrating/secrets/users
https://microcks.io/documentation/guides/nats-support/../../administrating/secrets/users
https://microcks.io/documentation/guides/mqtt-support/../../administrating/secrets/users
https://microcks.io/documentation/guides/aws-sqs-sns-support/../../administrating/secrets/users
https://microcks.io/documentation/guides/googlepubsub-support/../../administrating/secrets/users
https://microcks.io/documentation/guides/avro-messaging/../../documentation/

**Comment by soGit** [comment]
And one absolute link return 404 status code 

https://microcks.io/logo/

**Comment by lbroudoux** [comment]
It happens that pages under `documentation/using/advanced` are now directly located under `documentation/using` as the structure of website has been flatten... However, old pages are still present in the published website and some links still point to old pages. I will have a review of them.

**Comment by lbroudoux** [comment]
I've fixed some of the broken links mentioned above + merged the @soGit PR. Will have another look at it on Monday. Thanks!
