### ISSUE TITLE
Left side navigation broken layout 

### ISSUE THREAD

**Issue by soGit** [microcks/microcks.io#76]
### Describe the bug

As a user I want to be able to see left side navigation content without scrolling whole page to the end.

Also left side navigation content overlaps next section content on screens with width <= 1560px
<img width="462" alt="image" src="https://github.com/microcks/microcks.io/assets/10682798/84d93a89-dc67-4198-966d-1d906a053c5b">

### Expected behavior

- Left side navigation does not overlay bottom's content 
- Content from left side navigation available without scrolling the whole page

### Actual behavior

- Left side navigation overlay bottom's content
- User can not see left side navigation content without scrolling to the page end (if left side navigation content is bigger than view height) 

https://github.com/microcks/microcks.io/assets/10682798/e151c67d-1902-448a-881a-75ef185241fe

### How to Reproduce?

Open https://microcks.io/documentation/using/openapi/

**Comment by yada** [comment]
Thank you, @soGit, for bringing up this issue. It's a known problem that we've already slated for resolution in the upcoming documentation enhancement. I'll review your PR, as it seems like it could be a significant help in addressing this.

**Comment by yada** [comment]
By the way, we'd love for you to join the discussion on Discord regarding the ongoing documentation refactoring. Your insights would be greatly appreciated, see:
<img width="931" alt="Capture d’écran 2024-05-03 à 13 52 52" src="https://github.com/microcks/microcks.io/assets/552526/e51112e7-7935-48d8-9a6b-d9cb9b2629e9">

PS: I tagged you on the chat ;)
